Hw06
kajigor/fp-2024-cyp-spr pull request #100
Opened 2024-03-19 22:09 UTC by Fant1k34

2024-03-23 10:27 UTC, kajigor requested changes

2024-03-23 10:27 UTC, kajigor commented on src/IO.hs
> +    else getLineHelper array >>= myGetLine'
`myGetLine'` is not supposed to have an additional parameter.

2024-03-23 10:27 UTC, kajigor commented on src/IO.hs
> +    if last array == '\n'
Do you really need to inspect the array for the last character?

2024-03-23 10:27 UTC, kajigor commented on src/IO.hs
> +    helloUser
`interact :: (String -> String) -> IO ()` reads the line from the standard input, applies the input function to it, and outputs the result to the standard output.

2024-03-23 10:27 UTC, kajigor commented
1 ok

2024-04-02 18:08 UTC, Fant1k34 commented on src/IO.hs
> +    helloUser
Thank you, I've used this method in the implementation helloUser'

2024-04-02 18:09 UTC, Fant1k34 commented on src/IO.hs
> +    if last array == '\n'
Yes... I tried to delete this if-condition, but it's not working (endless IO operation unless ctlr + C is pressed)

2024-04-12 21:25 UTC, closed without merging