HW07 Georgii Ustinov [NUP]
kajigor/fp-2024-cyp-spr pull request #105
Opened 2024-03-24 15:47 UTC by Hardes1

I probably add part with IO, but not sure

2024-03-30 20:54 UTC, kajigor requested changes

2024-03-30 20:54 UTC, kajigor commented on hw07/src/Parser.hs
> +  satisfyEndOrWhiteSpace
The white space is not a part of an integer, so it is not a good idea to consume the space at this point. The same is true for the identifiers.

2024-03-30 20:54 UTC, kajigor commented on hw07/src/Parser.hs
> +  BinOp (binaryOperators ! op) f <$> parseExpression
`!` throws exception. Even though you checked that `op` is in the `binaryOperators` list by `member`, this may be lost in subsequent code rewrites. It's better to implement a parser `binaryOperator :: Parser BinaryOperator` which returns the binary operator value when succeeds. The same is true for the parser of unary operators

2024-03-30 20:54 UTC, kajigor commented on hw07/src/Parser.hs
> +    go [] _ = Left "Unary operator can't be empty"
This is one way to do it. You could also create a parser which succeeds after having consumed one word until the first white space encountered and then check if it's one of the unary operators.

2024-03-30 20:54 UTC, kajigor commented on hw07/src/Expr.hs
> +    Power -> performOpWithCheck (checkFirstArgIsNegative PowerBaseIsNegative) (**)) f s)
This is slightly unreadable: the fact that you construct a function in a case and then pass `f` and `s` to it is a bit convoluted. I'd better use a where clause to bind a name to the function.

2024-04-02 10:23 UTC, Hardes1 commented
I spent ~8 hours, to write this version of parser

2024-04-12 21:34 UTC, kajigor commented
Much better now.  1 2 ok

2024-04-12 21:34 UTC, closed without merging