feat(HW04): expression polymorphic type and expression simplifier
kajigor/fp-2024-cyp-spr pull request #106
Opened 2024-03-24 19:26 UTC by bas-kirill

✅ Tests passed:
<img width="632" alt="image" src="https://github.com/kajigor/fp-2024-cyp-spr/assets/39113667/12adcba9-9b55-4c5d-b1d6-63aff7212968">

2024-03-24 20:43 UTC, bas-kirill commented
HW05:
✅ Tests passed: 
<img width="248" alt="image" src="https://github.com/kajigor/fp-2024-cyp-spr/assets/39113667/cfda738c-53f9-4a66-bb21-101758dcf080">

🧪 Test coverage:
<img width="1509" alt="image" src="https://github.com/kajigor/fp-2024-cyp-spr/assets/39113667/e14ed92a-05dc-477b-88f5-f5b0cc585501">

2024-03-30 18:49 UTC, kajigor requested changes

2024-03-30 18:49 UTC, kajigor commented on src/Lib.hs
> +module Lib(Expr(..), Error(..), eval, EvalResult, Variables, simplify) where
People usually split definitions in multiple modules in the cases like this. `Expr` data type goes into one module along with the necessary instances, `Error` goes into the other, while evaluation and simplification go to the third.

2024-03-30 18:49 UTC, kajigor commented on test/Spec.hs
> +    in assertEqual "" expected actual
Whenever you don't intend to supply the string message for an assertion, better just use `@=?`

2024-04-12 21:26 UTC, closed without merging