HW07: Denis Shabanov
kajigor/fp-2024-cyp-spr pull request #107
Opened 2024-03-28 21:35 UTC by sickandpanik

Took me a lot of hours to complete (four, I think?) but I was mainly trying to understand how State monad works.

2024-03-30 21:13 UTC, kajigor requested changes

2024-03-30 21:13 UTC, kajigor commented on expression/src/ExprParser.hs
> +  "^" -> Exp
This function is not total; thus it'll throw an error at runtime. It's better to make a parser of a binary operator `parseBinOp :: Parser BinOperator` and call it to get the `op`. If there is an unexpected string instead of the binary operator, it'll fail as any other parser.

2024-03-30 21:13 UTC, kajigor commented on expression/src/ExprParser.hs
> +  "^" -> Exp
Imagine you need to add a new binary operator. Currently, it's too easy to forget to add the new binary operator in this function or in the `parseBinOp :: Parser String`

2024-03-30 21:13 UTC, kajigor commented on expression/src/Lib.hs
> +    outerExpr@(Operation (BinOp kind e1 e2)) -> case (kind, execState (eval e1) state, execState (eval e2) state) of
It's counterproductive to `execState` within the state monad. Have a look at how I did it in the original `Expr` file.

2024-04-12 21:37 UTC, kajigor commented on expression/src/ExprParser.hs
> +binOperatorsString = concatMap show (enumFrom minBound :: [BinOperator])
:+1: 

I've never thought of enumerating the constructors this way :)

2024-04-12 21:42 UTC, sickandpanik commented on expression/src/ExprParser.hs
> +binOperatorsString = concatMap show (enumFrom minBound :: [BinOperator])
> 👍
> 
> I've never thought of enumerating the constructors this way :)

what would be the other way? that was the simplest stackoverflow answer

2024-04-12 21:47 UTC, kajigor commented
ok

2024-04-12 21:47 UTC, closed without merging