HW 07 Grigorii Solnyshkin
kajigor/fp-2024-cyp-spr pull request #110
Opened 2024-04-02 18:47 UTC by GrigoriiSolnyshkin

Tasks 1-2 taken approximately 4 hours.

2024-04-12 22:23 UTC, kajigor requested changes

2024-04-12 22:23 UTC, kajigor commented on expr/src/Expr/Parser.hs
> +parsingError msg = Parser $ \s -> Left $ ParseError msg
Since `s` is not used, you could use `return` here instead of fussing with `Parser` and the lambda function

2024-04-12 22:23 UTC, kajigor commented on expr/src/Expr/Parser.hs
> +    c <- satisfies (`elem` "+-*/^")
In this function, you check your input twice for being one of the `"+-*/^"` symbols. You could instead write a parser that consumes one symbol from the input string and returns one of the BinOp constructors

2024-04-12 22:23 UTC, kajigor commented on expr/src/Expr/Parser.hs
> +parseSubexpr = (do Lit <$> parseNum) <|> (do Var <$> parseIdent) <|> (do parseBinop) <|> (do
No need to write `do` when there is only one line following it

2024-04-16 14:47 UTC, GrigoriiSolnyshkin commented on expr/src/Expr/Parser.hs
> +parsingError msg = Parser $ \s -> Left $ ParseError msg
But the error cannot be returned...

2024-04-22 09:50 UTC, kajigor commented on expr/src/Expr/Parser.hs
> +parsingError msg = Parser $ \s -> Left $ ParseError msg
Whoops, I don't remember what I was thinking about when wrote this comment. One thing that would make sense if you have this kind of function is to implement a `MonadFail` instance: https://hackage.haskell.org/package/base-4.19.1.0/docs/Prelude.html#t:MonadFail

2024-04-22 09:51 UTC, kajigor commented
1-2: ok

2024-04-22 09:51 UTC, closed without merging