HW07 Manninen Igor
kajigor/fp-2024-cyp-spr pull request #114
Opened 2024-04-02 20:41 UTC by imanninen

Spent around 11-12 hours on this homework.

2024-04-12 23:00 UTC, kajigor requested changes

2024-04-12 23:00 UTC, kajigor commented on hw07/src/Parser.hs
> +    s:q:r:t:l | [s, q, r, t] == "sqrt" -> Right ( l, "sqrt")
You can pattern match on chars directly: 

```
case str of 
  's' : 'q' : 'r' : 't' : l -> Right (l, "sqrt") 
```

2024-04-15 13:29 UTC, imanninen commented on hw07/src/Parser.hs
> +      then failParser "sqrt is not an ident!!" -- there it should fails but it not :(
sqrt is not an Identifier, and that is what it said. Or I miss something? Or if you about this comment, I forgot to remove it :)

2024-04-15 18:11 UTC, imanninen commented on hw07/app/Main.hs
> +    "exit" -> putStrLn "Bye!"
sad(

2024-04-22 09:57 UTC, kajigor commented on hw07/src/Parser.hs
> +      then failParser "sqrt is not an ident!!" -- there it should fails but it not :(
> if you about this comment, I forgot to remove it :)

Yep, it behaved as expected contrary to the comment

2024-04-22 10:03 UTC, kajigor commented
ok

2024-04-22 10:03 UTC, closed without merging