HW07: Nikita Dukin
kajigor/fp-2024-cyp-spr pull request #121
Opened 2024-04-10 19:36 UTC by Fant1k34

Сделал... Больше похоже на проект, чем на домашку по количеству заданий...

1. Перевел Functor, Applicative, Monad для Parser на Either (как договаривались на лекции)
2. Сделал реализацию Core Parser, чтобы маппить String в нашу структуру (на лекции мы не обобщали так)
3. Реализовал парсер для выражений
4. Перевел eval на работу со State Monad
5. Сделал консольное приложение в двух режимах: 1 - eval mode, 2 - simplify mode
6. Реализовал парсер для строки вводимых констант формата: x = ..., y = ..., z = ...
7. Устал

2024-04-13 12:32 UTC, kajigor commented
`sqrt` is not a valid variable name :) 

<img width="1429" alt="Screenshot 2024-04-13 at 2 31 34 PM" src="https://github.com/kajigor/fp-2024-cyp-spr/assets/1614576/2bb8f46e-2c94-4080-b7cf-71df49febb1a">

2024-04-13 12:33 UTC, kajigor commented
The expression parser is alright, but there are unexpected decision regarding the basic parser combinators

2024-04-13 12:33 UTC, kajigor requested changes

2024-04-13 12:33 UTC, kajigor commented on src/Lib.hs
> +  return (case (Data.Map.lookup variable (Data.Map.fromList env)) of
I would either pick working with a list or a map throughout `eval`. It's just pointless to create a map from the list every time you encounter a variable. If you want to stick to lists, they also have the `lookup` function

2024-04-13 12:33 UTC, kajigor commented on src/Lib.hs
> +    )
Whenever you only change the value under the `Right` constructor, it's better to use fmap `<$>`: 

```
return $ ((-1) *) <$> result 
``` 

This way, you may be sure that the error message is not changed and won't be changed during subsequent code rewrites.

2024-04-13 12:33 UTC, kajigor commented on src/ParserCore.hs
> +isFullyApplied = Parser (\input -> if (length input == 0) then Right (input, True) else Left ("Parse Error: String is not fully parsed -- " ++ input))
There is no point returning `Bool` here: you only ever return `True`, and even this value is ignored. 
Whether the parser succeeds evaluating to `Right` something or fails with `Left` is enough to understand what's happened. 
It's better to use the unit type: `isFullyApplied :: Parser ()`. This type's only value is meant to be ignored.

2024-04-13 12:33 UTC, kajigor commented on src/ParserCore.hs
> +isFullyApplied = Parser (\input -> if (length input == 0) then Right (input, True) else Left ("Parse Error: String is not fully parsed -- " ++ input))
Also, there's a function `null` that checks a list for emptiness.

2024-04-13 12:33 UTC, kajigor commented on src/ParserCore.hs
> +        )
Why do you need the `castFunction` anyway? 
As with any other function, it's always better for it to do as little as possible. 
If you need to transform the result, then just call `fmap` at the call sight.

2024-04-13 12:33 UTC, kajigor commented on src/ParserCore.hs
> +    return (letter ++ other)
Here you create a lot of singleton lists that you then concatenate, but may I ask you why?

2024-04-13 12:33 UTC, kajigor commented on src/ParserCore.hs
> +any p1 concatResults baseCase = some p1 concatResults <|> return baseCase
As with the `satisfy` above, it's quite unusual to pass additional function to concatenate results in these two combinators. 
Follow the single responsibility principle. 
Having the function `some` of type `Parser a -> Parser [a]` is much more universal.

2024-04-13 12:33 UTC, kajigor commented on src/ParserCore.hs
> +    return (letter ++ other)
If you had `any :: Parser a -> Parser [a]`, then this parser would look like the one below and be cleaner and easier to understand: 

``` 
parseIdent :: Parser String
parseIdent = do 
  letter <- satisfy isAlpha 
  others <- any (satisfy isAlphaNum) 
  return $ letter : others 
```

2024-04-13 12:33 UTC, kajigor commented on src/ParserExpr.hs
> +-- Заготовка для парсинга abc.de чисел. Но пока не сходятся типы Integral и Fractional -> Num
`fromIntegral`

2024-04-13 12:33 UTC, kajigor commented on src/Utils.hs
> +castCharToInt char
To Hoogle: `Char -> Int`

2024-04-18 13:34 UTC, Fant1k34 commented on src/Lib.hs
> +    )
Got it, thank you
I fixed it in those places that are not overloaded with some sort of logic

2024-04-18 13:37 UTC, Fant1k34 commented on src/ParserCore.hs
> +isFullyApplied = Parser (\input -> if (length input == 0) then Right (input, True) else Left ("Parse Error: String is not fully parsed -- " ++ input))
Yeap, great point and solution, thank you
I mentioned it too, but did not come with idea to fix it
Now I fixed it with Union () type as you adviced

2024-04-18 16:41 UTC, Fant1k34 commented on src/Utils.hs
> +castCharToInt char
I found! But I thought it would be unfair to implement Parser with "some embedded Parser" like Char to Int

2024-04-18 16:42 UTC, Fant1k34 commented on src/ParserExpr.hs
> +-- Заготовка для парсинга abc.de чисел. Но пока не сходятся типы Integral и Fractional -> Num
Fixed it, thanks
But it was out of the task, so I implemented it and have not used

2024-04-18 16:43 UTC, Fant1k34 commented on src/ParserCore.hs
> +        )
Got it, thank you for comment
I have never used fmap properly so now I figure out how can I apply it to this task

2024-04-18 16:44 UTC, Fant1k34 commented on src/ParserCore.hs
> +    return (letter ++ other)
Thanks, I fixed it ;)
I was need to create empty list to provide concatenation inside of the function

2024-04-18 16:49 UTC, Fant1k34 commented on src/Lib.hs
> +  return (case (Data.Map.lookup variable (Data.Map.fromList env)) of
Yeap, that makes sense
Fixed it, thanks

2024-04-22 10:09 UTC, closed without merging