HW08: Nikita Dukin
kajigor/fp-2024-cyp-spr pull request #123
Opened 2024-04-13 12:27 UTC by Fant1k34

2024-04-13 14:04 UTC, kajigor requested changes

2024-04-13 14:04 UTC, kajigor commented on test/Property.hs
> +      _ -> In
You can use `Gen.element` for generating one of the predefined set of values.

2024-04-13 14:04 UTC, kajigor commented on test/Property.hs
> +    )
What is this property supposed to check?

2024-04-13 14:04 UTC, kajigor commented on test/Property.hs
> +    value -> show False === show value ++ " got from " ++ show expr0
There is an easier way to fail a test: see `failure`

2024-04-13 14:04 UTC, kajigor commented on test/Property.hs
> +
Reduce code duplication by parameterizing this over the binary operation

2024-04-13 14:04 UTC, kajigor commented on test/Property.hs
> +  case evaluate (fmap fromInteger expr) [("x", 123)] of
You can also generate the var mapping :)

2024-04-13 14:05 UTC, kajigor commented
You did well. 👍  There are some aspects of how you write your code that you can improve.

2024-04-17 18:42 UTC, Fant1k34 commented on test/Property.hs
> +      _ -> In
Thank you for comment
It worked well and made code look beauty ;)

2024-04-17 18:54 UTC, Fant1k34 commented on test/Property.hs
> +    value -> show False === show value ++ " got from " ++ show expr0
Done, thanks

2024-04-17 23:05 UTC, Fant1k34 commented on test/Property.hs
> +
Thanks for comment, fixed it
I introduced several arguments to wrap subExpr, apply binary operation

2024-04-17 23:06 UTC, Fant1k34 commented on test/Property.hs
> +  case evaluate (fmap fromInteger expr) [("x", 123)] of
Yes, i can ahahaahha
But may be it would be enough writing tests for this time?))

2024-04-22 15:05 UTC, kajigor commented on test/Property.hs
> +  case evaluate (fmap fromInteger expr) [("x", 123)] of
![Uploading 1308168106001-188865597.jpg…]()

2024-04-22 15:08 UTC, kajigor commented
ok

2024-04-22 15:08 UTC, closed without merging