HW03: Nikita Dukin
kajigor/fp-2024-cyp-spr pull request #41
Opened 2024-02-23 15:17 UTC by Fant1k34

Я устав, но было интересно!

2024-02-23 17:57 UTC, kajigor requested changes

2024-02-23 17:57 UTC, kajigor commented on Main.hs
> +data Operator1 = Sqrt | Neg
I don't remember unary negation being in the task, but okay :)

2024-02-23 17:57 UTC, kajigor commented on Main.hs
> +  Sqrt == Neg = False
You can use wildcards so that not to write every possible combination

2024-02-23 17:57 UTC, kajigor commented on Main.hs
> +data Operator2 = Div | Mul | Plus | Min deriving (Eq)
What about `^`?

2024-02-23 17:57 UTC, kajigor commented on Main.hs
> +data Expr = Arg Double | Marg Operator1 Expr | CE Expr Operator2 Expr
:+1:

2024-02-23 17:57 UTC, kajigor commented on Main.hs
> +  CE expr1 op2 expr2 == Marg op1 value2 = False
Also wildcards here.

2024-02-23 17:57 UTC, kajigor commented on Main.hs
> +  Sqrt == Neg = False
And if the instance is standard, then it's better to derive it.

2024-02-23 17:57 UTC, kajigor commented on Main.hs
> +data Error = OutOfPossibleValuesError Operator1 Double | ZeroDivisionError Double Double
` ZeroDivisionError Double Double` -- is there more than one possible denominator when dividing by 0?)

2024-02-23 17:57 UTC, kajigor commented on Main.hs
> +cases = [
:+1:

2024-02-23 21:20 UTC, Fant1k34 commented on Main.hs
> +data Error = OutOfPossibleValuesError Operator1 Double | ZeroDivisionError Double Double
That's the origin way of legacy code ;)
Fixed it, thanks!

2024-02-23 21:24 UTC, Fant1k34 commented on Main.hs
> +  CE expr1 op2 expr2 == Marg op1 value2 = False
I hope that I get it in correct way, so I used "_ == _ = False"
Thanks for comment, it made code MUCH better ;)

2024-02-23 21:40 UTC, Fant1k34 commented on Main.hs
> +data Operator2 = Div | Mul | Plus | Min deriving (Eq)
Forgot ;)
Thank you, I added this operator, and added a new Error (IncorrectDegreeOfValue)

2024-02-23 21:42 UTC, Fant1k34 commented on Main.hs
> +  Sqrt == Neg = False
Okey, I fixed it with deriving ;)
Thank you!

2024-02-23 21:42 UTC, Fant1k34 commented on Main.hs
> +data Operator1 = Sqrt | Neg
Because I wanted to support negative values too)

2024-02-24 16:55 UTC, kajigor commented
Стало куда лучше :) 👍

2024-02-24 16:55 UTC, closed without merging