HW03 Gerasev Georgii
kajigor/fp-2024-cyp-spr pull request #54
Opened 2024-02-25 23:59 UTC by VenInf

It's not clear, how the "pow" operation should function, since it can be used as root, but doesn't have any potential errors in the description.

2024-02-26 11:26 UTC, kajigor commented on Main.hs
can be derived

2024-02-26 11:29 UTC, kajigor requested changes

2024-02-26 11:29 UTC, kajigor commented on Main.hs
> +            | ComplexError Error Error
:+1:

2024-02-26 11:29 UTC, kajigor commented on Main.hs
> +  (==) _ _ = False
can be derived

2024-02-26 11:29 UTC, kajigor commented on Main.hs
> +andExprError oper (Left expr1) (Left expr2) = Left (oper expr1 expr2)
Please use `Left` for errors and `Right` for the correct answers. The mnemonic is `Right` for the right answer

2024-02-26 11:29 UTC, kajigor commented on Main.hs
> +andExprError oper (Left expr1) (Left expr2) = Left (oper expr1 expr2)
It'll become clear why this is important once we learn about monads.

2024-02-26 11:29 UTC, kajigor commented on Main.hs
> +cases = [
Not all cases are covered

2024-02-26 17:49 UTC, VenInf commented
Fixed all of the commented parts.

2024-02-27 11:33 UTC, kajigor commented
ok

2024-02-27 11:33 UTC, closed without merging