HW04 Georgii Ustinov [NUP]
kajigor/fp-2024-cyp-spr pull request #63
Opened 2024-03-03 13:48 UTC by Hardes1

2024-03-04 18:30 UTC, kajigor requested changes

2024-03-04 18:30 UTC, kajigor commented on Main.hs
> +    fmap f (MyArrow g)  = MyArrow (f . g)
Have you proved the functor laws for these implementations?

2024-03-04 18:30 UTC, kajigor commented on Main.hs
> +  _ -> Left VariableIsUndefined
There is a function for this in the Prelude which you can find by hoogling.

2024-03-04 18:30 UTC, kajigor commented on Main.hs
> +  Square l -> Square (simplify l)
I would have changed the types of the helper function, so there is no need to construct and immediately deconstruct values for them. `simplifyMultiply :: Expr a -> Expr a -> Expr a`

2024-03-04 18:30 UTC, kajigor commented on Main.hs
> +  (Var "undefined", Left VariableIsUndefined),
There is one more significant case for the variables. Can you try to figure out which?

2024-03-05 07:07 UTC, Hardes1 commented on Main.hs
> +    fmap f (MyArrow g)  = MyArrow (f . g)
[proofs.pdf](https://github.com/kajigor/fp-2024-cyp-spr/files/14491626/proofs.pdf)

2024-03-05 07:43 UTC, Hardes1 commented on Main.hs
> +  (Var "undefined", Left VariableIsUndefined),
Hmm, only one thing which comes to mind is that variable value can be ambiguous, but I am not sure....

2024-03-05 09:58 UTC, kajigor requested changes

2024-03-05 09:58 UTC, kajigor commented on Main.hs
> +  (Var "undefined", Left VariableIsUndefined),
This is a little bit of overkill, but you are thinking in the right direction. What happens whenever there are two binding for a single variable?

2024-03-05 09:58 UTC, kajigor commented on Main.hs
> +      ri = lookup name (reverse map)
This is an overkill. This will also not work that easily if we were to switch to a different data type for substitutions.

2024-03-05 09:58 UTC, kajigor commented on Main.hs
> +  (Var "undefined", Left VariableIsUndefined),
My comment here was about the tests only, the implementation is fine.

2024-03-06 14:02 UTC, kajigor commented
ok

2024-03-06 14:05 UTC, kajigor commented
Sorry, closed this one by mistake.

2024-03-06 18:10 UTC, Hardes1 commented
So, what should I do next for this HW?

2024-03-07 16:47 UTC, closed without merging