HW04: Egor Kukoverov
kajigor/fp-2024-cyp-spr pull request #64
Opened 2024-03-04 01:09 UTC by ubuntuegor

2024-03-04 18:36 UTC, kajigor requested changes

2024-03-04 18:36 UTC, kajigor commented on Main.hs
> +  fmap f2 (MyArrow f1) = MyArrow $ f2 . f1
What about proofs of the Functor laws?

2024-03-04 18:36 UTC, kajigor commented on Main.hs
> +  (==) _ _ = False
Can be derived

2024-03-04 18:36 UTC, kajigor commented on Main.hs
> +eval (Var x) env = case find ((== x) . fst) env of
There is a function in Prelude for it which you can find by hoogling :)

2024-03-04 18:36 UTC, kajigor commented on Main.hs
> +    (Var "undefined", Left (UnknownVariable "undefined")),
There is one more important case for the variables, can you figure out which?

2024-03-04 18:36 UTC, kajigor commented on Main.hs
> +        _ -> Sqrt x'
You can also avoid using `let .. = .. in ..` like this: 
```
case simplify x of 
  Number 0 -> Number 0
  Number 1 -> Number 1 
  x -> Sqrt x
``` 

This makes variables more local, so you don't need to scroll back trying to find what exactly that `x'` is.

2024-03-04 18:36 UTC, kajigor commented on Main.hs
> +simplifyCases =
It can also be beneficial to test that simplify doesn't simplify expressions it is not supposed to simplify.

2024-03-04 23:24 UTC, ubuntuegor commented on Main.hs
> +  (==) _ _ = False
Technically not? Because `Add x y == Add y x` and `Mul x y == Mul y x` in this implementation

2024-03-04 23:32 UTC, ubuntuegor commented on Main.hs
> +eval (Var x) env = case find ((== x) . fst) env of
I found the function `find` in Hoogle but I'm pretty sure it's not available in the Prelude so I reimplemented it (because we haven't technically learned how to import yet :D)

2024-03-04 23:39 UTC, ubuntuegor commented on Main.hs
> +    (Var "undefined", Left (UnknownVariable "undefined")),
Hm, check that the environment gets passed to sub-expressions?

2024-03-05 10:05 UTC, kajigor requested changes

2024-03-05 10:05 UTC, kajigor commented on Main.hs
> +  (==) _ _ = False
Ah, I haven't noticed. This is a non-standard implementation of equality and cannot be derived, indeed. Sorry about that.

2024-03-05 10:05 UTC, kajigor commented on Main.hs
> +eval (Var x) env = case find ((== x) . fst) env of
There is another function that suits this context and is in Prelude :)

2024-03-05 10:05 UTC, kajigor commented on Main.hs
> +    (Var "undefined", Left (UnknownVariable "undefined")),
Nope, another :)

2024-03-13 16:05 UTC, closed without merging