HW04 Gerasev Georgii
kajigor/fp-2024-cyp-spr pull request #65
Opened 2024-03-04 20:52 UTC by VenInf

2024-03-05 10:06 UTC, kajigor commented on Main.hs
> +  fmap id (a -> b) = id . a -> b = a -> b
what is `a -> b`? This is not a value, it's a type

2024-03-05 10:15 UTC, kajigor requested changes

2024-03-05 10:15 UTC, kajigor commented on Main.hs
> +  fmap id (a -> b) = id . a -> b = a -> b
what is a -> b? This is not a value, it's a type

2024-03-05 10:15 UTC, kajigor commented on Main.hs
> +    lookup = find (\(x, _) -> x == v) vars
There is a function in Prelude which does exactly this.

2024-03-05 10:15 UTC, kajigor commented on Main.hs
> +simplify (Plus expr1 expr2) = Plus (simplify expr1) (simplify expr2) -- I wonder if there is a prettier way
Using a different representation for the `Expr` data type :)

2024-03-05 10:15 UTC, kajigor commented on Main.hs
> +    (Mult (Const 6) (Minus (Var "A") (Div (Pow (Var "A") (Var "C")) (Mult (Var "B") (Var "C")))), [("A", 1), ("B", 2), ("C", 3)], Right 5.0)
There is another significant case for variables.

2024-03-05 10:16 UTC, kajigor commented
<img width="682" alt="Screenshot 2024-03-05 at 11 11 44 AM" src="https://github.com/kajigor/fp-2024-cyp-spr/assets/1614576/053221e7-06eb-450a-b414-63d34c251e9f">

There are also at least two issues with simplification. These issues should be fixed and tests for them should be added.

2024-03-05 10:17 UTC, kajigor commented on Main.hs
> +simplify (Plus expr1 expr2) = Plus (simplify expr1) (simplify expr2) -- I wonder if there is a prettier way
(You don't need to rewrite the whole thing now, I'm gonna talk about it tomorrow, actually)

2024-03-05 10:18 UTC, kajigor commented
There isn't a solution for the sixth task.

2024-03-07 17:09 UTC, kajigor commented on Main.hs
> +simplify (Div expr1 expr2) = if (simple1 == simple2) && (simple1 /= Const 0) && (simple2 /= Const 0)
You only need to check one of the simple's for not equality to 0, btw

2024-03-07 17:11 UTC, kajigor commented
ok

2024-03-07 17:11 UTC, closed without merging

2024-03-07 18:17 UTC, VenInf commented
Was my "Num" implementation incorrect?