HW04: Kirill Chuvyzgalov
kajigor/fp-2024-cyp-spr pull request #71
Opened 2024-03-05 21:27 UTC by mrchuvyzgalov

2024-03-07 18:18 UTC, kajigor requested changes

2024-03-07 18:18 UTC, kajigor commented on Main.hs
> +    fmap f (To x y) = To x (f y)
This is not a data type for a function, it's a pair.

2024-03-07 18:18 UTC, kajigor commented on Main.hs
> +  | UnknownVariableError
It can be helpful to know which variable is unknown

2024-03-07 18:18 UTC, kajigor commented on Main.hs
> +        getValue (_, value) = value
`fst` and `snd`

2024-03-07 18:18 UTC, kajigor commented on Main.hs
> +    Right evaledX -> if evaledX < 0 then Left SquareRootError else Right $ sqrt evaledX
Reordering of the cases makes the pattern match on `Left` unnecessary

2024-03-08 21:16 UTC, mrchuvyzgalov commented on Main.hs
> +    Right evaledX -> if evaledX < 0 then Left SquareRootError else Right $ sqrt evaledX
I cannot do this because `extractValues` function returns `Either Error (a, a)`, but `eval` function returns `Either Error a`. 

If I change the order and replace `Left error -> Left error` with `error -> error`, the compiler says "Type mismatch".

2024-03-13 16:09 UTC, kajigor commented
ok

2024-03-13 16:09 UTC, closed without merging