HW05 Poshtarenko Andrei
kajigor/fp-2024-cyp-spr pull request #85
Opened 2024-03-12 22:35 UTC by EKCKABATOP54

2024-03-13 17:30 UTC, kajigor requested changes

2024-03-13 17:30 UTC, kajigor commented on expr/src/Expr.hs
> +module Expr where
It's better to split the functionality into multiple modules, each of which does its own thing

2024-03-13 17:31 UTC, kajigor commented
Have you made tasty work in the end?

2024-03-13 19:42 UTC, EKCKABATOP54 commented on expr/src/Expr.hs
> +module Expr where
The implementation of Error depends on Expr for more detailed error reporting. Therefore, when dividing into modules, a cyclic dependence is obtained

2024-03-13 19:45 UTC, EKCKABATOP54 commented
> Have you made tasty work in the end?
Yes. For some reason an error occurred on Windows, but on Linux everything is ok

I have one more question. The PR of the fourth homework closed with the comment “ok”, which means, as I understand it, everything is ok. But the score for task 4 remained the same as before the last fix. So I would like to ask if the scores in the table are correct?

2024-03-14 14:32 UTC, kajigor commented
HW04: fixed

2024-03-16 09:37 UTC, EKCKABATOP54 commented on expr/src/Expr.hs
> +module Expr where
Fixed

2024-03-18 16:23 UTC, kajigor commented
ok

2024-03-18 16:23 UTC, closed without merging