HW06 Gerasev Georgii
kajigor/fp-2024-cyp-spr pull request #88
Opened 2024-03-16 21:27 UTC by VenInf

2024-03-18 16:29 UTC, kajigor commented on monads/src/Either.hs
> +  return = pure
No need to implement `return`, it has this exact implementation by default.

2024-03-18 16:36 UTC, kajigor requested changes

2024-03-18 16:36 UTC, kajigor commented on monads/src/Either.hs
> +  fmap (f . g) (MyRight x) = MyRight (f.g) x = fmap f (MyRight g x) = fmap f . fmap g (MyRight x)
The first equality is incorrect.

2024-03-18 16:36 UTC, kajigor commented
1.1 ok, the rest is not implemented

2024-03-19 15:28 UTC, VenInf commented on monads/src/Either.hs
> +  fmap (f . g) (MyRight x) = MyRight (f.g) x = fmap f (MyRight g x) = fmap f . fmap g (MyRight x)
Tried to fix it.
Not quite sure where the error is.

2024-03-22 11:12 UTC, kajigor commented
ok

2024-03-22 11:12 UTC, closed without merging